### ISSUE TITLE
[Feature Request] Any chance of having the tiles include links to news posts?

### ISSUE THREAD

**Issue by Jules-A** [kenofnz/priconne-en-event-timer#1]
It would be nice if there were links to the relevant news posts or if there isn't one, the source of the event info.

**Comment by trunghieumickey** [comment]
My fork have one if you interested. By the way, i want to give a big thanks to the original owner who powered my fork, making it posible ! Would love to push back some changes if he allow it.

**Comment by Jules-A** [comment]
> My fork have one if you interested. By the way, i want to give a big thanks to the original owner who powered my fork, making it posible ! Would love to push back some changes if he allow it.

I just checked the live version: https://trunghieumickey.github.io/priconne-en-event-timer/ and that's not what I mean. I was after hyperlinked event images (just an example) directing to the news post the information came from. For example, the Suzume banner would be https://www.crunchyroll.com/anime-news/2021/06/16-1/princess-connect-re-dives-summer-of-fun-continues-with-suzume-summer and S.Karyl would be https://www.crunchyroll.com/anime-news/2021/07/02/princess-connect-re-dives-karyl-summer-drags-in-more-summer-fun

**Comment by trunghieumickey** [comment]
> > My fork have one if you interested. By the way, i want to give a big thanks to the original owner who powered my fork, making it posible ! Would love to push back some changes if he allow it.
> 
> I just checked the live version: https://trunghieumickey.github.io/priconne-en-event-timer/ and that's not what I mean. I was after hyperlinked event images (just an example) directing to the news post the information came from. For example, the Suzume banner would be https://www.crunchyroll.com/anime-news/2021/06/16-1/princess-connect-re-dives-summer-of-fun-continues-with-suzume-summer and S.Karyl would be https://www.crunchyroll.com/anime-news/2021/07/02/princess-connect-re-dives-karyl-summer-drags-in-more-summer-fun

Can you open a separate issue at my fork. I would love to help if you do so

**Comment by trunghieumickey** [comment]
> > My fork have one if you interested. By the way, i want to give a big thanks to the original owner who powered my fork, making it posible ! Would love to push back some changes if he allow it.
> 
> I just checked the live version: https://trunghieumickey.github.io/priconne-en-event-timer/ and that's not what I mean. I was after hyperlinked event images (just an example) directing to the news post the information came from. For example, the Suzume banner would be https://www.crunchyroll.com/anime-news/2021/06/16-1/princess-connect-re-dives-summer-of-fun-continues-with-suzume-summer and S.Karyl would be https://www.crunchyroll.com/anime-news/2021/07/02/princess-connect-re-dives-karyl-summer-drags-in-more-summer-fun

Solved at my fork ! You can take a look.
P/S : Maybe I should detach from main repository since I don't want to use same issue board with the project owner.

**Comment by kenofnz** [comment]
@trunghieumickey nice choice of layouts, though I only intend on having a minimal amount of items on screen to support as many mobile screen sizes as possible. Which means leaving things out like block separators. I'll consider adding it as a view option.

@Jules-A The source of the info usually comes from data mining the in-game events. I don't normally go look up the article to get the info other than the occasional announcement happening before the events are put in the game data. I can add that in but theres no guarantee that article link will always be present.

**Comment by kenofnz** [comment]
Implemented
